# Generated by Django 6.0.3 on 2026-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
